# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jtobin.ca
url:              http://jtobin.ca
baseurl:          /

author:
  name:           'Jared Tobin'

paginate:         5

# Custom vars
# version:          2.1.0

twitter: https://twitter.com/jaredtobin
medium: https://medium.com/@jaredtobin
github: https://github.com/jtobin
keybase: https://keybase.io/jtobin
