# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        ':title'

# Setup
title:            jtobin.ca
url:              http://jtobin.ca
baseurl:          /

author:
  name:           'Jared Tobin'

paginate:         5

twitter: https://twitter.com/jaredtobin
medium:  https://medium.com/@jaredtobin
github:  https://github.com/jtobin
keybase: https://keybase.io/jtobin
instagram: https://instagram.com/jaredrtobin
se: https://stackexchange.com/users/1074581/jtobin?tab=accounts
