# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        ':title'

# Setup
title:            jtobin.io
url:              http://jtobin.io
baseurl:          /

author:
  name:           'Jared Tobin'

paginate:         5

twitter: https://twitter.com/jaredtobin
medium:  https://medium.com/@jaredtobin
github:  https://github.com/jtobin
keybase: https://keybase.io/jtobin
pgp: https://pgp.mit.edu/pks/lookup?op=vindex&search=0x710A5FDAE32D77E7
instagram: https://instagram.com/jaredrtobin
se: https://stackexchange.com/users/1074581/jtobin?tab=accounts
